# Workflow to render Quarto documents
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Render Quarto Docs
permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install R dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Debug: List files and check project
        shell: bash
        run: |
          ls -la
          quarto check

      - name: Render Quarto documents
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: diamonds_plot.qmd

      - name: Upload rendered files
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: rendered-quarto
          path: |
            *.html

      - name: Commit rendered files
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.html
          git commit -m "Re-built Quarto documents" || echo "No changes to commit"
          git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
